version: '3'

services:
  hello-service:
    build: .
    image: hello-app-dev
    container_name: hello-app-dev
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    ports:
      - ${PORT}:${PORT}
