version: '3.5'

services:
  hello-service:
    build: .
    container_name: hello-service
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    ports:
      - ${PORT}:${PORT}
